version: '3'
services:
  jinux:

    build: .
    image: ${DOCKER_USER_ID}/jinux-assignment4

  production:
    image: ${DOCKER_USER_ID}/jinux-assignment4:${BUILD_NUMBER}
    ports:
      - 80:80

~


